### ISSUE TITLE
ParserError: Expected ',' but got identifier   --> project:/contracts/Date.sol:44:34:

### ISSUE THREAD

**Issue by Cyberodd** [kiecodes/nft#1]
Hi, 
I followed along on the YouTube video to learn how to create Dapps but got an error while running "truffle test" for the Date contract. Out put below

PS C:\DPUMD\FirstTruffle> truffle test
Using network 'test'.

Compiling your contracts...
===========================
> Compiling .\contracts\Date.sol
> Compiling .\contracts\Date.sol
> Compiling .\contracts\Migrations.sol

ParserError: Expected ',' but got identifier
  --> project:/contracts/Date.sol:44:34:
   |
44 |         require(msg.value == (10 finney), "claiming a date costs 10 finney");
   |                                  ^^^^^^

Compilation failed. See above.
Truffle v5.4.3 (core: 5.4.3)
Node v14.17.3

Is there a declaration for "10 finney" missing? 
Your correspondence is appreciated

**Comment by thekie** [comment]
Hello, the support for "finney" was dropped in newer solidity versions. Which version are you using in your truffle-config.js?

**Comment by Cyberodd** [comment]
0.8.0

**Comment by Cyberodd** [comment]
Is there an alternative I could use or should I just get started on another tutorial series?

**Comment by thekie** [comment]
Instead of using `10 finney` you can use `0.01 ether`.

**Comment by thekie** [comment]
I hope that has helped. If you have further questions please don't hesitate to ask. Cheers!

**Comment by Cyberodd** [comment]
Certainly helpful, thank you
