### ISSUE TITLE
TypeError: Operator + not compatible with types int256 and uint256

### ISSUE THREAD

**Issue by Cyberodd** [kiecodes/nft#2]
Line 151 has a type error??
TypeError: Operator + not compatible with types int256 and uint256
   --> project:/contracts/Date.sol:151:23:
    |
151 |         year = uint16(int(yoe) + era * 400 + (month <= 2 ? 1 : 0));
    |                       ^^^^^^^^^^^^^^^^^^^^

After about a week turning this over, referencing the fundamentals and documentation, I still don't have a solution for this. The lack of comments in the code notwithstanding, I'd like to know how you made it work. Are the differences between Mac and Windows that substantial?

**Comment by thekie** [comment]
Are you current with master branch? I think i fixed that for solc 0.8.0

**Comment by Cyberodd** [comment]
Hmmm, I hadn't used clone to replicate the repo, I was just going along with the tutorial's progress, but let me give it a shot and get back to you

**Comment by thekie** [comment]
Here's the commit if you want to compare: https://github.com/kiecodes/nft/commit/988f64bf5d2c127bbb7e76bdf4f548337673dffd

**Comment by thekie** [comment]
I am closing this now. If you have any more questions feel free to open this issue again.
